const Permission = [
  { permission: "user.create", isSelected: false },
  { permission: "user.read", isSelected: false },
  { permission: "user.update", isSelected: false },
  { permission: "user.delete", isSelected: false },
  { permission: "factory.create", isSelected: false },
  { permission: "factory.read", isSelected: false },
  { permission: "factory.update", isSelected: false },
  { permission: "factory.delete", isSelected: false },
  { permission: "typeOfFactory.create", isSelected: false },
  { permission: "typeOfFactory.read", isSelected: false },
  { permission: "typeOfFactory.update", isSelected: false },
  { permission: "typeOfFactory.delete", isSelected: false },
  { permission: "itemFactory.create", isSelected: false },
  { permission: "itemFactory.read", isSelected: false },
  { permission: "itemFactory.update", isSelected: false },
  { permission: "itemFactory.delete", isSelected: false },
  { permission: "ourRequest.create", isSelected: false },
  { permission: "ourRequest.read", isSelected: false },
  { permission: "ourRequest.update", isSelected: false },
  { permission: "ourRequest.delete", isSelected: false },
  { permission: "paymentFactory.create", isSelected: false },
  { permission: "paymentFactory.read", isSelected: false },
  { permission: "paymentFactory.update", isSelected: false },
  { permission: "paymentFactory.delete", isSelected: false },
  { permission: "paymentWay.create", isSelected: false },
  { permission: "paymentWay.read", isSelected: false },
  { permission: "paymentWay.update", isSelected: false },
  { permission: "paymentWay.delete", isSelected: false },
];

module.exports = Permission;
